apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: gg786ykoa-go-gitops
  description: This is GitOps manifest for gg786ykoa-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=gg786ykoa-go
    backstage.io/kubernetes-id: gg786ykoa-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: gg786ykoa-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:gg786ykoa-go
